print("Welcome to Miney!")
print("")
print("Type the following lines to connected to the currently running minetest game:")
print("")
print("import miney")
print("mt = miney.Minetest()")
print("")
print("You can now use the \"mt\" object to interact with minetest.")
print("Type mt.doc() to open the documentation in your webbrowser.")
